## Chpater 13 - Introducing Pandas Objects

In [1]:
import numpy as np
import pandas as pd

- At a very basic level, Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices.

### The Pandas Series Object

- A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array as follows:

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1])
print(data)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

- The `Series` combines a sequence of values with an explicit sequence of indices, which we can access with the `values` and `index` attributes.
    - The `values` are simply a familiar NumPy array:
    - The `index` is an array-like object of type `pd.Index`:

In [3]:
print(data.values)
print(data.index)

[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)

- Like with a NumPy array, data can be accessed by the associated index via the familiar Python square-bracket notation:

In [4]:
print(data[1])
print(data[1:3])

0.5
1    0.50
2    0.75
dtype: float64

#### Series as Generalized NumPy Array

- From what we’ve seen so far, the `Series` object may appear to be basically interchangeable with a one-dimensional NumPy array. The essential difference is that while the NumPy array has an **implicitly defined integer** index used to access the values, the Pandas Series has an **explicitly defined index** associated with the values.
- This explicit index definition gives the `Series` object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type.

In [5]:
# Using strings as an index
data = pd.Series([0.25, 0.5, 0.75, 1], index = ['a', 'b', 'c', 'd'])
print(data)
print(data['a'])

# Using noncontiguous or nonsequential indices
data = pd.Series([0.25, 0.5, 0.75, 1], index = [2, 5, 3, 7])
print(data)
print(data[7])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.25
2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64
1.0

#### Series as Specialized Dictionary

- In this way, you can think of a Pandas `Series` a bit like a specialization of a Python dictionary. A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a Series is a structure that maps typed keys to a set of typed values. This typing is important: just as the type-specific compiled code behind a NumPy array makes it more efficient than a Python list for certain operations, the type information of a Pandas `Series` makes it more efficient than Python dictionaries for certain operations.

In [6]:
population_dict = {'California': 39538223, 'Texas': 29145505,  'Florida': 21538187, 'New York': 20201249, 'Pennsylvania': 13002700}
population = pd.Series(population_dict)
print(population)

print(population['California'])

# Unlike a dictionary, though, the Series also supports array-style operations such as slicing:
print(population['California':'Florida'])

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
dtype: int64
39538223
California    39538223
Texas         29145505
Florida       21538187
dtype: int64

#### Constructing Series Objects

- We’ve already seen a few ways of constructing a Pandas Series from scratch. All of them are some version of the following: `pd.Series(data, index=index)`, where index is an optional argument, and data can be one of many entities.

In [7]:
# Data can be a list or NumPy array, 
# in which case index defaults to an integer sequence.
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [8]:
# Data can be a scalar,
# which is repeated to fill the specified index.
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [9]:
# Data can be a dictionary,
# in which case index defaults to the dictionary keys
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [10]:
# In each case,the index can be explicitly set to control the order or the subset of keys used.
pd.Series({2:'a', 1:'b', 3:'c'}, index=[1, 2])

1    b
2    a
dtype: object

### The Pandas DataFrame Object

- The next fundamental structure in Pandas is the DataFrame. Like the Series object discussed in the previous section, the DataFrame can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.

#### DataFrame as Generalized NumPy Array

- If a `Series` is an analog of a one-dimensional array with explicit indices, a `DataFrame` is an analog of a two-dimensional array with explicit row and column indices.

In [11]:
population_dict = {'California': 39538223, 'Texas': 29145505,  'Florida': 21538187, 'New York': 20201249, 'Pennsylvania': 13002700}
area_dict = {'California': 423967, 'Texas': 695662, 'Florida': 170312,  'New York': 141297, 'Pennsylvania': 119280}

population = pd.Series(population_dict)
area = pd.Series(area_dict)

states = pd.DataFrame({'population': population, 'area': area})
print(states)

              population    area
California      39538223  423967
Texas           29145505  695662
Florida         21538187  170312
New York        20201249  141297
Pennsylvania    13002700  119280

- Like the Series object, the DataFrame has an index attribute that gives access to the index labels.
- Additionally, the DataFrame has a columns attribute, which is an Index object holding the column labels.

In [12]:
print(states.index)
print(states.columns)

Index(['California', 'Texas', 'Florida', 'New York', 'Pennsylvania'], dtype='object')
Index(['population', 'area'], dtype='object')

#### DataFrame as Specialized Dictionary

- Similarly, we can also think of a `DataFrame` as a specialization of a dictionary. Where a dictionary maps a key to a value, a `DataFrame` maps a column name to a `Series` of column data.

In [13]:
states['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

#### Constructing DataFrame Objects

- A Pandas `DataFrame` can be constructed in a variety of ways:

In [14]:
# From a single Series object
pd.DataFrame(population, columns=['population'])

              population
California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700

In [15]:
# From a list of dicts
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4

- Even if some keys in the dictionary are missing, Pandas will fill them in with `NaN` values

In [16]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [17]:
# From a dictionary of Series objects
pd.DataFrame({'population': population,  'area': area})

              population    area
California      39538223  423967
Texas           29145505  695662
Florida         21538187  170312
New York        20201249  141297
Pennsylvania    13002700  119280

In [18]:
# From a two-dimensional NumPy array
pd.DataFrame(np.random.rand(3, 2),  columns=['foo', 'bar'], index=['a', 'b', 'c'])

        foo       bar
a  0.124894  0.884117
b  0.448735  0.579954
c  0.161303  0.709748

In [19]:
# From a NumPy structured array
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
pd.DataFrame(A)

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

## The Pandas Index Object

- As you’ve seen, the Series and DataFrame objects both contain an explicit index that lets you reference and modify data. This Index object is an interesting structure in itself, and it can be thought of either as an immutable array or as an ordered set (technically a multiset, as Index objects may contain repeated values). Those views have some interesting consequences in terms of the operations available on Index objects. As a simple example, let’s construct an Index from a list of integers:

In [20]:
ind = pd.Index([2, 3, 5, 7, 11])
print(ind)

Index([2, 3, 5, 7, 11], dtype='int64')

#### Index as Immutable Array

In [21]:
ind[1]

np.int64(3)

In [22]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [23]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64

#### Index as Ordered Set

- Pandas objects are designed to facilitate operations such as joins across datasets, which depend on many aspects of set arithmetic. The Index object follows many of the conventions used by Python’s built-in set data structure, so that unions, intersections, differences, and other combinations can be computed in a familiar way:

In [25]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [26]:
indA.intersection(indB)

Index([3, 5, 7], dtype='int64')

In [27]:
ind.union(indB)

Index([2, 3, 5, 7, 11], dtype='int64')

In [28]:
indA.symmetric_difference(indB)

Index([1, 2, 9, 11], dtype='int64')