## Chapter 14 - Data Indexing and Selection

In [38]:
import pandas as pd
import numpy as np

### Data Selection in Series

#### Series as Dictionary

- Like a dictionary, the Series object provides a mapping from a collection of keys to a collection of values:

In [39]:
data = pd.Series(np.linspace(0.25, 1, 4), index = ['a', 'b', 'c', 'd'])
print(data['b'])

0.5

In [40]:
# Using dictionary-like Python expressions
print('a' in data)
print(data.keys())
print(list(data.items()))

True
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [41]:
# Modifying
data['e'] = 1.25
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

#### Series as One-Dimensional Array

In [42]:
# Slicing by explicit index
print(data['a':'c'])

# Slicing by implicit integer index
print(data[0:2])

# Masking
print(data[(data > 0.3) & (data < 0.8)])

# Fancy indexing
print(data[['a', 'e']])

a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
dtype: float64
b    0.50
c    0.75
dtype: float64
a    0.25
e    1.25
dtype: float64

- **IMPORTANT:** Notice that when slicing with an explicit index (e.g., `data['a':'c']`), the final index is included in the slice, while when slicing with an implicit index (e.g., `data[0:2]`), the final index is excluded from the slice.

#### Indexers: `loc` and `iloc`

- If your Series has an explicit integer index, an indexing operation such as `data[1]` will use the explicit indices, while a slicing operation like `data[1:3]` will use the implicit Python-style indices.
- Because of this potential confusion in the case of integer indexes, Pandas provides some special indexer attributes that explicitly expose certain indexing schemes. These are not functional methods, but attributes that expose a particular slicing interface to the data in the Series.

In [43]:
data = pd.Series(['a', 'b', 'c'], index = [1, 3, 5])
print(data)

print(data[1])

print(data[1:3])

1    a
3    b
5    c
dtype: object
a
3    b
5    c
dtype: object

First, the `loc` attribute allows indexing and slicing that always references the explicit index:

In [44]:
data.loc[1]

'a'

- The `iloc` attribute allows indexing and slicing that always references the implicit Python-style index:

In [45]:
data.iloc[1]

'b'

### Data Selection in DataFrames

#### DataFrame as Dictionary

In [46]:
area = pd.Series({'California': 423967, 'Texas': 695662,  'Florida': 170312, 'New York': 141297, 'Pennsylvania': 119280})
pop = pd.Series({'California': 39538223, 'Texas': 29145505,  'Florida': 21538187, 'New York': 20201249, 'Pennsylvania': 13002700})
data = pd.DataFrame({'area':area, 'pop':pop})

print(data)

                area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

- The individual Series that make up the columns of the DataFrame can be accessed via dictionary-style indexing of the column name.
- Equivalently, we can use attribute-style access with column names that are strings.

In [47]:
print(data['area'])
print(data.area)

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64
California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

- Like with the `Series` objects discussed earlier, this dictionary-style syntax can also be used to modify the object, in this case adding a new column:

In [48]:
data['density'] = data['pop'] / data['area']
print(data)

                area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

#### DataFrame as Two-Dimensional Array

- As mentioned previously, we can also view the `DataFrame` as an enhanced twodimensional array.

In [49]:
data.values

array([[4.23967000e+05, 3.95382230e+07, 9.32577842e+01],
       [6.95662000e+05, 2.91455050e+07, 4.18960717e+01],
       [1.70312000e+05, 2.15381870e+07, 1.26463121e+02],
       [1.41297000e+05, 2.02012490e+07, 1.42970120e+02],
       [1.19280000e+05, 1.30027000e+07, 1.09009893e+02]])

- We can transpose the full DataFrame to swap rows and columns.

In [50]:
data.T

           California         Texas       Florida      New York  Pennsylvania
area     4.239670e+05  6.956620e+05  1.703120e+05  1.412970e+05  1.192800e+05
pop      3.953822e+07  2.914550e+07  2.153819e+07  2.020125e+07  1.300270e+07
density  9.325778e+01  4.189607e+01  1.264631e+02  1.429701e+02  1.090099e+02

- Using the `iloc` indexer, we can index the underlying array as if it were a simple NumPy array (using the implicit Pythonstyle index), but the DataFrame index and column labels are maintained in the result:

In [51]:
data.iloc[:3, :2]

              area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

- Similarly, using the `loc` indexer we can index the underlying data in an array-like style but using the explicit index and column names:

In [52]:
data.loc[:'Florida', :'pop']

              area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

- In the loc indexer we can combine masking and fancy indexing as follows:

In [53]:
data.loc[data.density > 120, ['pop', 'density']]

               pop     density
Florida   21538187  126.463121
New York  20201249  142.970120

- Any of these indexing conventions may also be used to set or modify values; this is done in the standard way that you might be accustomed to from working with NumPy:

In [54]:
data.iloc[0, 2] = 90
print(data)

                area       pop     density
California    423967  39538223   90.000000
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893